### ISSUE TITLE
"type":"illegal_argument_exception"

### ISSUE THREAD

**Issue by dim321** [reidmorrison/semantic_logger#293]
### Environment
* Ruby Version - 2.3.1
* Rails Version Rails - 5.2.4.5
* Semantic Logger Version - 4.7.4
* Rails Semantic Logger Version - 4.5.1
* Elasticsearch - 8.14.3
* application.rb:
*     if ENV["LOG_TO_ELASTIC"]
      config.semantic_logger.add_appender(
        appender:    :elasticsearch,
        url:         ENV.fetch('LOG_TO_ELASTIC_URL', "http://localhost:9200"),
        index:       "myapp-#{Rails.env}-index",
        data_stream: true
      )
    end
* Full Stack Trace, an exception is being raised:

2024-07-29 18:30:49.469896 F [112569:SemanticLogger::Appender::Elas loggable.rb:45] SemanticLogger::Appender::Elasticsearch -- [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}
2024-07-29 18:30:49.470070 E [112569:SemanticLogger::Appender::Elas] SemanticLogger::Appender::Elasticsearch -- Async: Restarting due to exception -- Exception: Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}
/home/dim/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
/home/dim/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/dim/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
/home/dim/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
/home/dim/.rvm/gems/ruby-2.3.1/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/bulk.rb:54:in `bulk'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/elasticsearch.rb:176:in `write_to_elasticsearch'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/elasticsearch.rb:169:in `batch'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async_batch.rb:82:in `block in process_messages'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async_batch.rb:62:in `loop'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async_batch.rb:62:in `process_messages'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async.rb:121:in `process'
/home/dim/.rvm/gems/ruby-2.3.1/gems/semantic_logger-4.7.4/lib/semantic_logger/appender/async.rb:77:in `block in thread'

### Expected Behavior

Rails app send logs to Elasticsearch

### Actual Behavior

Rails app raise exception when try to start

**Comment by reidmorrison** [comment]
This is a version mismatch rather than a bug in current Semantic Logger.

The config in this report relies on two things that did not exist in 4.7.4:

1. **`data_stream: true` was silently ignored in 4.7.4.** That keyword was not added until later, so it fell through into the Elasticsearch client args and did nothing. Data-stream support first shipped in **v4.9.0**.

2. **`_type` was emitted unconditionally in 4.7.4.** Its bulk action/metadata line always included `"_type"`, which Elasticsearch 8.x rejects (`unknown parameter [_type]`). Making `_type` conditional on the Elasticsearch client version first shipped in **v4.15.0**.

Current `master` (and any release >= 4.15.0) handles both cases: with `data_stream: true` the bulk header is `{"create" => {}}` (no `_type`), and otherwise `_type` is only added for Elasticsearch ruby gem versions < 7.

**Resolution:** please upgrade `semantic_logger` to the latest release (4.18.0). Note that the elasticsearch ruby gem in this report (7.5.0) is also very old relative to an ES 8.x server, so consider bumping that as well.

Closing as resolved by upgrade, but happy to reopen if the problem persists on a current version.
